/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Master.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import koneksi.koneksi;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class CariDataPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form CariDataPelanggan
     */
    ArrayList<String> text = new ArrayList<>();
    ArrayList<String> text1 = new ArrayList<>();

    public CariDataPelanggan() {
        initComponents();
//        Table();
        Table1();

    }

    void Table1() {
        DefaultTableModel model = (DefaultTableModel) tabelPelanggan.getModel();;
        try {
            int no = 1;
            String sql = "select * from 1718157_pelanggan";
            koneksi DB = new koneksi();
            Connection mySql = DB.getConnection();
            Statement state = mySql.createStatement();
            ResultSet res = state.executeQuery(sql);
            while (res.next()) {
                String a = res.getString(3);
                System.out.println(a);
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            tabelPelanggan.setModel(model);
        } catch (Exception e) {
        }
        int barang = tabelPelanggan.getRowCount();
        System.out.println(barang);
        txtPelanggan.setText(String.valueOf(barang));
    }

//    void Table(){
//        DefaultTableModel model = (DefaultTableModel) tabelPelanggan1.getModel();;^
//        try {
//            int no=1;
//            String sql = "select * from 1718157_barang";
//            koneksi DB = new koneksi();
//            Connection mySql = DB.getConnection();
//            Statement state = mySql.createStatement();
//            ResultSet res = state.executeQuery(sql);
//        while(res.next()){
//            String a = res.getString(3);
//            System.out.println(a);
//            model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
//        }
//        tabelPelanggan1.setModel(model);
//         } catch (Exception e) {
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        txtPelanggan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Id Pelanggan", "Nama Pelanggan", "Alamat Pelanggan", "No. Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPelanggan);
        if (tabelPelanggan.getColumnModel().getColumnCount() > 0) {
            tabelPelanggan.getColumnModel().getColumn(0).setMaxWidth(50);
            tabelPelanggan.getColumnModel().getColumn(1).setMaxWidth(100);
            tabelPelanggan.getColumnModel().getColumn(2).setMaxWidth(150);
            tabelPelanggan.getColumnModel().getColumn(3).setMaxWidth(300);
            tabelPelanggan.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        jLabel1.setText("Pelanggan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(txtPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        int baris = tabelPelanggan.rowAtPoint(evt.getPoint());
        text.add(" ");
        text.add(" ");
        text.add(" ");
        text.add(" ");
        text.add(tabelPelanggan.getValueAt(baris, 1).toString());
        text.add(tabelPelanggan.getValueAt(baris, 2).toString());
        text.add(tabelPelanggan.getValueAt(baris, 3).toString());
        text.add(tabelPelanggan.getValueAt(baris, 4).toString());
        txtPelanggan.setText(tabelPelanggan.getValueAt(baris, 1).toString());

        PreparedStatement ps;
        String query = "INSERT INTO `dpelanggan`(`1718157_IdPelanggan`, `1718157_NmPelanggan`, `1718157_Alamat`, `1718157_NoTelp`) VALUES (?,?,?,?)";

        try {
            ps = koneksi.getConnection().prepareStatement(query);
            ps.setString(1, tabelPelanggan.getValueAt(baris, 1).toString());
            ps.setString(2, tabelPelanggan.getValueAt(baris, 2).toString());
            ps.setString(3, tabelPelanggan.getValueAt(baris, 3).toString());
            ps.setString(4, tabelPelanggan.getValueAt(baris, 4).toString());
            if (ps.executeUpdate() > 0) {
            }
        } catch (SQLException ex) {
            Logger.getLogger(EntryPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new EntrySuratPesan(text).setVisible(true);
        
    }//GEN-LAST:event_tabelPelangganMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariDataPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTextField txtPelanggan;
    // End of variables declaration//GEN-END:variables
}
