/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Master.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import koneksi.koneksi;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CariDataBarang extends javax.swing.JFrame {

    /**
     * Creates new form CariDataPelanggan
     */
    ArrayList<String> text = new ArrayList<>();
    public CariDataBarang() {
        initComponents();
        Table();   
    }
    void Table(){
        DefaultTableModel model = (DefaultTableModel) tabelPelanggan1.getModel();;
        try {
            int no=1;
            String sql = "select 1718157_KdBarang, 1718157_NmBarang, 1718157_Satuan, 1718157_HrgBarang from 1718157_barang b where b.1718157_KdBarang not in (select KdBarang from d_detil)";
            koneksi DB = new koneksi();
            Connection mySql = DB.getConnection();
            Statement state = mySql.createStatement();
            ResultSet res = state.executeQuery(sql);
        while(res.next()){
            String a = res.getString(3);
            System.out.println(a);
            model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
        }
        tabelPelanggan1.setModel(model);
         } catch (Exception e) {
        }
        int barang = tabelPelanggan1.getRowCount();
        System.out.println(barang);
        txtBarang.setText(String.valueOf(barang));
    }
//    void asiji(){
//        try {
//            koneksi DB = new koneksi();
//            Connection mySql = DB.getConnection();
//            String sql = "select * from dpelanggan";
////            String sql = "select * from 1718157_pelanggan order by 1718157_IdPelanggan DESC";
//            Statement state = mySql.createStatement();
//            ResultSet rs = state.executeQuery(sql);
////            text.add(tabelPelanggan1.getValueAt(baris, 1).toString());
////            text.add(tabelPelanggan1.getValueAt(baris,2).toString());
////            text.add(tabelPelanggan1.getValueAt(baris,3).toString());
////            text.add(tabelPelanggan1.getValueAt(baris,4).toString());
//            String a = rs.getString(2);
//            System.out.println(1);
//            text.add("Asimek");
//            text.add(" ");
//            text.add(" ");
//            text.add(" ");
//            new EntrySuratPesan(text).setVisible(true);
//                dispose();
//        }catch(SQLException e){
//            
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan1 = new javax.swing.JTable();
        txtBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelPelanggan1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kd Barang", "Nama Barang", "Satuan", "Harga Barang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPelanggan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelanggan1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan1);

        jLabel2.setText("Total Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPelanggan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelanggan1MouseClicked
        int baris = tabelPelanggan1.rowAtPoint(evt.getPoint());
//        ArrayList<String> text = new ArrayList<>();
        try {
            koneksi DB = new koneksi();
            Connection mySql = DB.getConnection();
            String sql = "select * from dpelanggan";
//            String sql = "select * from 1718157_pelanggan order by 1718157_IdPelanggan DESC";
            Statement state = mySql.createStatement();
            ResultSet rs = state.executeQuery(sql);
            text.add(tabelPelanggan1.getValueAt(baris, 1).toString());
            text.add(tabelPelanggan1.getValueAt(baris,2).toString());
            text.add(tabelPelanggan1.getValueAt(baris,3).toString());
            text.add(tabelPelanggan1.getValueAt(baris,4).toString());
            if(rs.next()){
                String a = rs.getString(1);
                System.out.println(a);
                text.add(a);
                text.add(rs.getString(2));
                text.add(rs.getString(3));
                text.add(rs.getString(4));
            }else{
                text.add(" ");
                text.add(" ");
                text.add(" ");
                text.add(" ");
            }
            
            new EntrySuratPesan(text).setVisible(true);
                dispose();
        }catch(SQLException e){
            
        }
//            text.add(tabelPelanggan1.getValueAt(baris, 1).toString());
//            text.add(tabelPelanggan1.getValueAt(baris,2).toString());
//            text.add(tabelPelanggan1.getValueAt(baris,3).toString());
//            text.add(tabelPelanggan1.getValueAt(baris,4).toString());
//            text.add("Asimek");
//            text.add(" ");
//            text.add(" ");
//            text.add(" ");
//            new EntrySuratPesan(text).setVisible(true);
//                dispose();
        txtBarang.setText(tabelPelanggan1.getValueAt(baris, 1).toString());
//        new EntrySuratPesan(text).setVisible(true);
    }//GEN-LAST:event_tabelPelanggan1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariDataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelPelanggan1;
    private javax.swing.JTextField txtBarang;
    // End of variables declaration//GEN-END:variables
}
